# Generated by Django 5.0.2 on 2026-06-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='theme1', max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('logo_link', models.URLField(blank=True, max_length=500, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('search_bar_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('sub_note', models.TextField(blank=True, null=True)),
                ('other_note', models.TextField(blank=True, null=True)),
                ('other_subnote', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=dict, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('add_on_options', models.JSONField(blank=True, default=dict, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.category')),
            ],
        ),
    ]
