# Generated by Django 5.0.2 on 2026-06-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='client',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.client'),
            preserve_default=False,
        ),
    ]
