# Generated by Django 5.0.2 on 2026-06-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
