# Generated by Django 5.0.2 on 2026-06-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
