# Generated by Django 5.0.2 on 2026-06-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
