# Generated by Django 5.0.2 on 2026-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='payment_methods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='policy_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
