# Generated by Django 5.0.2 on 2026-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_clientsettings_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='policy_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
