# Generated by Django 5.0.2 on 2026-06-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_alter_clientsettings_policy_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='delivery_end',
            field=models.CharField(default='19:00', max_length=5),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='delivery_start',
            field=models.CharField(default='10:00', max_length=5),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='enable_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='enable_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='pickup_end',
            field=models.CharField(default='21:00', max_length=5),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='pickup_start',
            field=models.CharField(default='09:00', max_length=5),
        ),
    ]
