# Generated by Django 5.0.2 on 2026-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_clientsettings_delivery_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='is_store_open',
            field=models.BooleanField(default=True),
        ),
    ]
