# Generated by Django 5.0.2 on 2026-06-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_clientsettings_is_store_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cake_inscription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
