# Generated by Django 5.0.2 on 2026-06-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_product_cake_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cake_inscription',
        ),
    ]
